nginx:
  build: .
  ports:
    - "80:80"
  links:
    - cartodb:cartodb.localhost

mapproxy:
  build: ./docker-mapproxy/
  ports:
    - "8282:8282"

cartodb:
  build: ./docker-cartodb/
  links:
    - postgres:postgres
#    - redis:redis
  ports:
    - "3000:3000"
    - "8080:8080"
    - "8181:8181"

postgres:
  hostname: postgres
  build: ./docker-postgis/
